### ISSUE TITLE
Create a separate file for the contract address configuration.

### ISSUE THREAD

**Issue by VladislavIvanov** [LimeChain/etherlime-shape-angular#3]

**Comment by ochikov** [comment]
Hello @VladislavIvanov and thank you for the reported issue,

I have updated the repository, so now we have a config.json file with parameter inside for the address of the deployed conctract. I also make some changes to the documentation.

**Comment by ochikov** [comment]
This commit solves the issue: https://github.com/LimeChain/etherlime-shape-angular/commit/8ab91c2358df0eb06323a9ed1868eeaf1e9e2f4f

I am closing it.
